#!/bin/sh
#
# Copyright (C) 2010  Jeremy Bae
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

#  echo -e "GET / HTTP/1.0\n\n" | nc -w 1 [host] [port]

function usage
{
  echo "Usage: $0 <host>"
}

if [ $# -ne 1 ]; then
  usage
  exit
fi

TARGET=$1
#PORTS=`seq 1 65535` # about 18 hours
#PORTS=`seq 1 1024` # about 17 minuites
PORTS="21 22 23 25 80 135 137 138 139 8009 8080 9090"

for PORT in $PORTS
do
  RESULT=`echo -e 'print "HEAD / HTTP/1.0\n\n"' | nc -w 1 $TARGET $PORT`
  STRLEN=`expr "$RESULT" : '.*'`
  if [ $STRLEN -gt 0 ]; then
    echo "$TARGET:$PORT (open)"
  fi
done
